name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'  # Usa la versión de R que prefieras

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Check URL Connectivity
        run: |
          curl -I https://archivos.midagri.gob.pe/index.php/s/deZQjkzmbodFyG6/download || exit 1

      - name: Run R CMD check
        run: |
          R CMD check .
